#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS


#define INITIAL_PROMPT "Welcome to the Bank!\nWho are you?\n1. Admin\t2. Customer\t3.Employee\t4.Manager\nPress 0 to exit\nEnter your choice!"

/*COMMON TEXT */

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT "a1"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number"
#define GET_CUSTOMER_ID "Enter the customer ID"
#define GET_EMPLOYEE_ID "Enter the employee ID"

#define ERRON_INPUT_FOR_NUMBER "It seems like you have entered a string or an invalid number when a correct number was expected!\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"


#define EMPLOYEE_ID_DOESNT_EXIT "No employee could be found for the given ID"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIT "No employee could be found for the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

/*------------------------------------------------------------------------------------------*/
/*ADMIN SPECIFIC TEXT*/

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! \nEnter your credentials !"
#define ADMIN_LOGIN_SUCCESS "You've successfully logged into the admin!"

// ADMIN MENU
#define ADMIN_MENU "1. Add Bank Employee\n2. Modify Employee Information\n3. Modify Customer Information\n4. Delete Employee Account\n5. Change Password\nPress 0 to logout"

// ADD EMPLOYEE
#define ADMIN_ADD_EMPLOYEE "Enter the details for the employee\n"
#define ADMIN_ADD_EMPLOYEE_NAME "What is the employee's name?"
#define ADMIN_ADD_EMPLOYEE_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_EMPLOYEE_AGE "What is the employee's age?"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_LOGIN "The autogenerated login ID for the employee is : "
#define AUTOGEN_EMPLOYEE_PASSWORD "emp12345" // append to end of next string macro
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_EMPLOYEE_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD ACCOUNT
#define ADMIN_ADD_EMPLOYEE_NUMBER "The newly created employee number is :"

// DELETE ACCOUNT
#define ADMIN_DEL_EMPLOYEE_NO "What is the employee number of the employee you want to delete?"
#define ADMIN_DEL_EMPLOYEE_ACCOUNT_SUCCESS "This employee's account has been successfully deleted\nRedirecting you to the main menu ...^"

// MODIFY EMPLOYEE INFO
#define ADMIN_MOD_EMPLOYEE_ID "Enter the ID of the employee who's information you want to edit"
#define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress 0 to cancel"
#define ADMIN_MOD_EMPLOYEE_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_EMPLOYEE_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_EMPLOYEE_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_EMPLOYEE_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "Logging you out now admin!$"

/*------------------------------------------------------------------------------------------*/
/*EMPLOYEE SPECIFIC TEXT*/

// LOGIN WELCOME
#define EMPLOYEE_LOGIN_WELCOME "Welcome dear employee! \nEnter your credentials !"
#define EMPLOYEE_LOGIN_SUCCESS "You've successfully logged into your account!"

// EMPLOYEE MENU
#define EMPLOYEE_MENU "1. Add Customer\n2. Modify Customer Information\n3. Process Loan Application\n4. Approve Loan or Reject Loan\n5. View Assigned Loan Applications\n6. Get Transaction Details\n7. Change Password\n8. Delete Customer Account\nPress 0 to logout"

// ADD CUSTOMER
#define EMPLOYEE_ADD_CUSTOMER_PRIMARY "Enter the details for the primary customer\n"
#define EMPLOYEE_ADD_CUSTOMER_NAME "What is the customer's name?"
#define EMPLOYEE_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define EMPLOYEE_ADD_CUSTOMER_AGE "What is the customer's age?"
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "qwerty12345" // append to end of next string macro
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define EMPLOYEE_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD ACCOUNT
#define EMPLOYEE_ADD_ACCOUNT_NUMBER "The newly created account's number is :"

// DELETE ACCOUNT
#define EMPLOYEE_DEL_ACCOUNT_NO "What is the account number of the account you want to delete?"
#define EMPLOYEE_DEL_ACCOUNT_SUCCESS "This account has been successfully deleted\nRedirecting you to the main menu ...^"
#define EMPLOYEE_DEL_ACCOUNT_FAILURE "This account cannot be deleted since it is not empty\nRedirecting you to the main menu ...^"

// MODIFY CUSTOMER INFO (ADMIN AND EMPLOYEE CAN ACCESS)
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress 0 to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define EMPLOYEE_LOGOUT "Logging you out now employee!$"
/*------------------------------------------------------------------------------------------*/

/*MANAGER SPECIFIC TEXT*/

//LOGIN WELCOME
#define MANAGER_LOGIN_WELCOME "Welcome dear manager! Enter your credentials to gain access to your account!"
#define MANAGER_LOGIN_SUCCESS "Welcome manager!"
#define MANAGER_LOGOUT "Logging you out now dear manager! $"

// MANAGER MENU
#define MANAGER_MENU "1. Activate or Deactivate Customer Account\n2. Assign Loan Application Processes to Employees\n3. Review Customer Feedback\nPress 0 to logout"


/*------------------------------------------------------------------------------------------*/
/*CUSTOMER SPECIFIC TEXT*/

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome customer!"

#define CUSTOMER_LOGOUT "Logging you out now dear customer! $"

// ADMIN MENU
#define CUSTOMER_MENU "1. Get Customer Details\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\n7. Transfer Funds\n8. Apply for Loan\n9. Give Feedback\nPress 0 to logout"

#define ACCOUNT_DEACTIVATED "It seems your account has been deactivated!^"

#define DEPOSIT_AMOUNT "How much is it that you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT "How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

/*------------------------------------------------------------------------------------------*/

#define EMPLOYEE_FILE "./records/employee.bank"
#define ACCOUNT_FILE "./records/account.bank"
#define CUSTOMER_FILE "./records/customer.bank"
#define TRANSACTION_FILE "./records/transactions.bank"
#define LOAN_FILE "./records/loan.bank"

#endif
